project_id = "qadfjbgfdejmhblgvaef"

[functions.google-auth-callback]
verify_jwt = false

[functions.google-calendar-sync]
verify_jwt = false

[functions.gupshup-templates]
verify_jwt = false

[functions.wpp-template-suggest]
verify_jwt = false

[functions.wpp-webhook]
verify_jwt = false

[functions.lat-bot-agent]
verify_jwt = false

[functions.lat-routing-engine]
verify_jwt = false

[functions.lat-email-agent]
verify_jwt = false

[functions.lat-process-queue]
verify_jwt = false
